version: '3'
services:
  webapp:
    build:
        context: .
        args:
            ENSEMBL_DIVISION: ensembl          
            ENSEMBL_RELEASE: 95
            ENSEMBL_GENOMES_RELEASE: 42
#    image: sanjayboddu/ensembl-browser:experiemntal_release_94.1 
    links:
        - db:ensembl_docker_database
    depends_on: 
        - db
    tty: true
    ports:
        - "8000:8080"
  db:
     image: ensemblorg/ensembl-browser-db:experiemntal_release_95.1
     tty: true
