# Ensembl uses docker-compose file only due to dependency on sessions database. We could pass this dependency as command line argument while running the container but it is easier with docker-compose file. 

version: '3'
services:

  browser:
    image: sanjayboddu/ensembl-browser:experiemntal_release_94.1 
    networks:
      - my-custom-network    
    depends_on: 
        - ensembl_docker_database
    tty: true
    ports:
        - "8000:8080"

  ensembl_docker_database:
     image: ensemblorg/ensembl-browser-db:experiemntal_release_95.1
     networks:
       - my-custom-network
     tty: true


networks:
    my-custom-network:
        driver: bridge
